title: Programming Discussion Discord
description: >
  The Programming Discussions Discord server is an
  open, friendly and welcoming environment to discuss
  or ask questions about programming.

theme: jekyll-theme-cayman
